branches:
  only:
    - master
    - 1.x

language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - 7.1
  - 7.2
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      dist: precise
    - php: 5.3
      dist: precise
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: PHP_CS_FIXER_VERSION=1.*
    - php: 5.6
      env: PHP_CS_FIXER_VERSION=2.*@dev
    - php: 5.6
      env: SYMFONY_VERSION=2.7.*
    - php: 5.6
      env: SYMFONY_VERSION=2.8.*
    - php: 5.6
      env: SYMFONY_VERSION=3.0.*
    - php: 5.6
      env: SYMFONY_VERSION=3.1.*
    - php: 5.6
      env: SYMFONY_VERSION=3.2.*
    - php: 7.1
      env: SYMFONY_VERSION=3.3.*
    - php: 7.1
      env: SYMFONY_VERSION=3.4.*
    - php: 7.1
      env: SYMFONY_VERSION=4.0.*
  allow_failures:
    - php: nightly
    - env: PHP_CS_FIXER_VERSION=2.*@dev
    - env: SYMFONY_VERSION=3.2.*@dev

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_install:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-rm xdebug.ini; fi;

install:
  - composer global require 'phpunit/phpunit:^4.0 || ^5.0' satooshi/php-coveralls:@stable codeclimate/php-test-reporter:@stable sllh/composer-lint:@stable --prefer-dist --no-interaction
  - if [ "$PHP_CS_FIXER_VERSION" != "" ]; then composer require "friendsofphp/php-cs-fixer:${PHP_CS_FIXER_VERSION}" --no-update; fi;
  - if [ "$SYMFONY_VERSION" != "" ]; then composer require "symfony/symfony:${SYMFONY_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

before_script:
  - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then echo "zend_extension=xdebug.so" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi;

script:
  - composer validate
  - phpunit -c phpunit.xml.dist --coverage-clover build/logs/clover.xml

after_script:
  - coveralls -v
  - test-reporter
