language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - nightly
  - hhvm

env:
  global:
    - PATH="$HOME/.composer/vendor/bin:$PATH"

matrix:
  fast_finish: true
  include:
    - php: 5.3
      env: COMPOSER_FLAGS="--prefer-lowest"
    - php: 5.6
      env: PHP_CS_FIXER_VERSION=2.*
    - php: 5.6
      env: PHP_CS_FIXER_VERSION=3.*@dev
  allow_failures:
    - php: nightly
    - php: hhvm
    - php: hhvm-nightly
    - env: PHP_CS_FIXER_VERSION=3.*@dev

sudo: false

cache:
  directories:
    - $HOME/.composer/cache/files

before_script:
  - composer selfupdate
  - composer config -g github-oauth.github.com $GITHUB_OAUTH_TOKEN
  - composer global require phpunit/phpunit:@stable --no-update
  - composer global update --prefer-dist --no-interaction
  - if [ "$PHP_CS_FIXER_VERSION" != "" ]; then composer require "fabpot/php-cs-fixer:${PHP_CS_FIXER_VERSION}" --no-update; fi;
  - composer update --prefer-dist --no-interaction $COMPOSER_FLAGS

script:
  - make test
  # Nightly builded with https://nightli.es/
  # See also: https://github.com/travis-ci/travis-ci/issues/582#issuecomment-124136045
  - ./bridge styleci:config:check

after_script:
  - php vendor/bin/coveralls -v
  - php vendor/bin/test-reporter
